(() => {
const Q=s=>document.querySelector(s), A=s=>[...document.querySelectorAll(s)], canvas=Q('#city-map'), ctx=canvas.getContext('2d');
const base={name:'台風「白波」',start:360,rain:480,flood:600,peak:.92,budget:680,duration:72};
const facilities=[['hospital','市民総合病院','✚',7.5,2.2,'医療',['power','water'],92],['power','中央変電所','ϟ',4.1,5.7,'電力',['road'],96],['water','西部浄水場','≈',1.8,3.1,'水道',['power'],100],['fire','港湾消防署','✦',9.2,5.4,'消防',['road','power'],94],['logistics','東物流センター','▣',10.1,2.8,'物流',['road','power'],89]];
let S, C={...base};
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const time=()=>{let d=Math.floor(S.m/1440)+1,t=S.m%1440;return 'DAY '+String(d).padStart(2,'0')+' · '+String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0')};
const add=(type,text,kind='')=>{S.feed.unshift({t:time().split(' · ')[1],type,text,kind});S.feed=S.feed.slice(0,9)};
function reset(next=C){C={...base,...next};S={m:C.start,run:false,speed:1,spent:0,safe:100,trust:72,rumor:7,flood:0,roads:100,teams:0,shelters:0,evac:0,priority:'power',comms:'verify',feed:[],done:false,h:Object.fromEntries(facilities.map(f=>[f[0],f[7]])),selected:null};add('SYSTEM','シナリオを初期化しました。災害対策本部は待機中。','info');render()}
function calc(){let h=S.m/60, p=clamp((h-C.flood/60)/8*C.peak*100);S.flood=h<C.flood/60?0:p;S.roads=clamp(100-S.flood*.68+(S.teams?5:0));S.h.power=clamp(96-Math.max(0,S.flood-37)*1.25+(S.priority==='power'?S.teams*1.2:0));S.h.water=clamp(100-Math.max(0,60-S.h.power)*.72-S.flood*.12+(S.priority==='water'?S.teams*1.2:0));S.h.hospital=clamp(92-Math.max(0,60-S.h.power)*.5-Math.max(0,55-S.h.water)*.35+(S.priority==='medical'?S.teams*1.5:0));S.h.fire=clamp(94-Math.max(0,55-S.roads)*.7);S.h.logistics=clamp(89-Math.max(0,60-S.roads)*.85);S.safe=clamp(100-S.flood*.38-Math.max(0,55-S.roads)*.3+S.evac*.26+S.shelters*3);S.rumor=clamp(S.rumor+Math.max(0,S.flood-18)*.11+(S.comms==='silent'?1.1:S.comms==='rapid'?.28:.52)-(S.comms==='verify'?.52:.2));S.trust=clamp(S.trust+(S.comms==='verify'?.14:S.comms==='silent'?- .16:.02)-S.rumor*.007)}
function step(){if(!S.run||S.done)return;S.m+=15*S.speed;calc();if(S.flood>22&&!S.floodEvent){S.floodEvent=true;add('FLOOD','港南・海岸地区で道路冠水を確認。救助隊の経路が制限されています。','danger')}if(S.h.power<64&&!S.powerEvent){S.powerEvent=true;add('POWER','中央変電所の浸水リスクが上昇。計画停電の可能性があります。','danger')}if(S.rumor>35&&!S.rumorEvent){S.rumorEvent=true;add('MEDIA','避難所の満員を示す未確認情報が急速に拡散しています。','danger')}render()}
const health=v=>v>=70?'':v>=40?'warn':'fail';
function render(){Q('#game-time').textContent=time();Q('#simulation-status').textContent=S.run?'シミュレーション中':'待機中';Q('#pause-button').textContent=S.run?'Ⅱ 停止':'▶ 開始';Q('#headline').textContent=S.flood?'台風「白波」通過中 — 浸水指数 '+Math.round(S.flood)+' / 100':'台風「白波」接近中 — 予想到達まで '+String(Math.max(0,18-Math.floor(S.m%1440/60))).padStart(2,'0')+':00';Q('#ticker-text').textContent=S.rumor>35?'未確認情報が拡散中。公式発表方針を見直してください。':S.flood>25?'低地で冠水を確認。道路と電力設備を監視中です。':'災害対策本部は気象情報を監視中です。';Q('#alert-strip').classList.toggle('crisis',S.flood>25);Q('#alert-level').textContent=S.flood>60?'緊急対応':S.flood>25?'警戒レベル 3':'訓練シナリオ';
let infra=Math.round((S.h.power+S.h.water+S.h.hospital+S.roads)/4), metrics=[['住民安全',S.safe,Math.round(128400*(100-S.safe)/100)+' 人が支援を必要とする可能性'],['インフラ',infra,'重要施設・道路網の総合稼働率'],['市民信頼',S.trust,'デマ拡散指数 '+Math.round(S.rumor)+' / 100'],['予算',100-S.spent/C.budget,Math.round(C.budget-S.spent)+' / '+C.budget+' 対策ポイント']];Q('#metric-list').innerHTML=metrics.map(x=>'<article class="metric"><div class="metric-top"><span>'+x[0]+'</span><strong>'+Math.round(x[1])+(x[0]==='予算'?'':'%')+'</strong></div><div class="bar"><i style="width:'+clamp(x[1])+'%;background:'+(x[1]<40?'var(--danger)':x[1]<70?'var(--amber)':'var(--accent)')+'"></i></div><small>'+x[2]+'</small></article>').join('');
Q('#facility-list').innerHTML=facilities.map(f=>'<li data-id="'+f[0]+'"><span class="facility-name"><i class="facility-icon">'+f[2]+'</i>'+f[1]+'</span><span class="facility-state '+health(S.h[f[0]])+'">'+Math.round(S.h[f[0]])+'%</span></li>').join('');A('[data-id]').forEach(e=>e.onclick=()=>{S.selected=facilities.find(f=>f[0]===e.dataset.id);render()});
Q('#system-grid').innerHTML=[['電力',S.h.power],['水道',S.h.water],['通信',98-S.flood*.22],['医療',S.h.hospital],['物流',S.h.logistics],['道路',S.roads]].map(x=>'<article class="system"><p>'+x[0]+'</p><strong>'+Math.round(x[1])+'%</strong><small class="'+health(x[1])+'">'+(x[1]>=70?'NORMAL':x[1]>=40?'WATCH':'CRITICAL')+'</small></article>').join('');
let f=S.selected;Q('#district-card').innerHTML=f?'<p class="eyebrow">'+f[4]+' FACILITY</p><h3>'+f[1]+'</h3><p>この施設は <b>'+f[5].map(x=>({power:'電力',water:'水道',road:'道路'}[x])).join(' / ')+'</b> に依存しています。</p><dl><div><dt>稼働状態</dt><dd>'+Math.round(S.h[f[0]])+'%</dd></div><div><dt>到達経路</dt><dd>'+(S.roads>=60?'確保':'迂回中')+'</dd></div></dl>':'<p class="eyebrow">CITY OVERVIEW</p><h3>新港市 全域</h3><p>地区または施設を選択すると、被害と依存関係を確認できます。</p><dl><div><dt>警戒レベル</dt><dd class="safe">WATCH</dd></div><div><dt>復旧優先</dt><dd>'+S.priority+'</dd></div></dl>';
let commands=[['evac','避難勧告を発令','早期実施ほど安全を守るが、市民信頼を少し消費。',70],['shelter','避難所を開設','収容力を確保し、避難勧告の効果を高める。',95],['dispatch','救助隊を派遣','道路状態に応じて迂回経路を探索する。',80],['repair','緊急復旧班を出動','選択中の復旧優先度に追加人員を配備。',105]];Q('#command-grid').innerHTML=commands.map(c=>'<button class="command" data-c="'+c[0]+'" '+(C.budget-S.spent<c[3]?'disabled':'')+'><b>'+c[1]+'</b><small>'+c[2]+'</small><em>コスト '+c[3]+'</em></button>').join('');A('[data-c]').forEach(e=>e.onclick=()=>act(e.dataset.c));Q('#event-feed').innerHTML=S.feed.map(e=>'<li class="'+e.kind+'"><time>'+e.t+'</time><b>'+e.type+'</b><span>'+e.text+'</span></li>').join('');Q('#route-readout').textContent='道路網: '+Math.round(S.roads)+'% 通行可能 / 救助隊 '+S.teams+'隊';draw()}
function act(id){let cost={evac:70,shelter:95,dispatch:80,repair:105}[id];if(C.budget-S.spent<cost)return;S.spent+=cost;if(id==='evac'){S.evac=clamp(S.evac+22);S.trust-=S.flood<10?4:1;add('ACTION','高リスク区域に避難勧告を発令しました。','info')}if(id==='shelter'){S.shelters=Math.min(12,S.shelters+3);add('ACTION','避難所を3か所開設しました。','info')}if(id==='dispatch'){S.teams=Math.min(8,S.teams+2);add('ACTION',S.roads<55?'冠水道路を避ける迂回経路を計算中。':'救助隊が主要道路を通り現地へ向かっています。','info')}if(id==='repair'){S.teams=Math.min(8,S.teams+3);add('ACTION',S.priority+'を最優先に緊急復旧班を配備しました。','info')}calc();render()}
function draw(){let w=canvas.clientWidth,h=canvas.clientHeight;if(!w)return,ctx.clearRect(0,0,w,h);let cw=w/12,ch=h/8;ctx.fillStyle='#081c25';ctx.fillRect(0,0,w,h);for(let r=0;r<8;r++)for(let c=0;c<12;c++){let coast=r>=6||c===0,a=Math.max(0,(S.flood*(coast?1.28:.58)-18)/100)*.72;ctx.fillStyle='rgba('+Math.round(30-10*a)+','+Math.round(78+65*a)+','+Math.round(84+125*a)+','+(.22+a)+')';ctx.fillRect(c*cw+2,r*ch+2,cw-4,ch-4);ctx.strokeStyle='rgba(105,201,181,.13)';ctx.strokeRect(c*cw+2,r*ch+2,cw-4,ch-4)}ctx.strokeStyle=S.roads<55?'rgba(255,119,103,.63)':'rgba(106,208,191,.40)';for(let i=1;i<12;i+=2){ctx.beginPath();ctx.moveTo(i*cw,0);ctx.lineTo(i*cw,h);ctx.stroke()}for(let i=1;i<8;i+=2){ctx.beginPath();ctx.moveTo(0,i*ch);ctx.lineTo(w,i*ch);ctx.stroke()}facilities.forEach(f=>{let x=f[3]*cw,y=f[4]*ch,v=S.h[f[0]];ctx.beginPath();ctx.arc(x,y,S.selected===f?14:10,0,Math.PI*2);ctx.fillStyle=v<40?'#ff7767':v<70?'#f7c76a':'#5cf2c2';ctx.fill();ctx.fillStyle='#071019';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 12px sans-serif';ctx.fillText(f[2],x,y+1);ctx.textAlign='left';ctx.textBaseline='alphabetic'})}
function resize(){let r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}
Q('#pause-button').onclick=()=>{S.run=!S.run;add('SYSTEM',S.run?'時間進行を開始しました。':'時間進行を停止しました。','info');render()};A('.speed-button').forEach(b=>b.onclick=()=>{S.speed=+b.dataset.speed;A('.speed-button').forEach(x=>x.classList.toggle('active',x===b))});A('[data-priority]').forEach(b=>b.onclick=()=>{S.priority=b.dataset.priority;A('[data-priority]').forEach(x=>x.classList.toggle('active',x===b));Q('#priority-note').textContent='選択した都市機能を優先復旧します。'});A('[data-comms]').forEach(b=>b.onclick=()=>{S.comms=b.dataset.comms;A('[data-comms]').forEach(x=>x.classList.toggle('active',x===b));Q('#comms-note').textContent=b.dataset.comms==='verify'?'信頼を守りつつ情報を届けます。':b.dataset.comms==='rapid'?'情報は速いが、誤報は信頼を損ねます。':'デマが拡散しやすくなります。'});
canvas.onclick=e=>{let r=canvas.getBoundingClientRect(),cw=r.width/12,ch=r.height/8,x=e.clientX-r.left,y=e.clientY-r.top;let hit=facilities.find(f=>Math.hypot(f[3]*cw-x,f[4]*ch-y)<25);if(hit){S.selected=hit;Q('#map-readout').textContent='選択: '+hit[1];render()}};
Q('#save-button').onclick=()=>{localStorage.setItem('shinko-save',JSON.stringify({C,S}));Q('#save-status').textContent='現在の状況を保存しました。'};Q('#load-button').onclick=()=>{let x=localStorage.getItem('shinko-save');if(!x)return Q('#save-status').textContent='保存データがありません。';let d=JSON.parse(x);C=d.C;S=d.S;S.run=false;render();Q('#save-status').textContent='保存データを読み込みました。'};Q('#editor-button').onclick=()=>{Q('#scenario-json').value=JSON.stringify(C,null,2);Q('#editor-dialog').showModal()};Q('#apply-scenario').onclick=()=>{try{let x=JSON.parse(Q('#scenario-json').value);if(!x.name||typeof x.flood!=='number')throw Error('name と flood が必要です');Q('#editor-dialog').close();reset(x)}catch(e){alert('JSONを適用できません: '+e.message)}};Q('#finish-button').onclick=()=>{S.run=false;S.done=true;let infra=Math.round((S.h.power+S.h.water+S.h.hospital+S.roads)/4),score=Math.round(S.safe*.4+infra*.28+S.trust*.18+(100-S.spent/C.budget)*.14);Q('#report-content').innerHTML='<div class="dialog-header"><div><p class="eyebrow">AFTER ACTION REPORT</p><h2>'+C.name+' 終了報告</h2></div><button class="close-button">×</button></div><div class="report-score">'+score+'<small> / 100</small></div><p>'+(score>=75?'都市機能をおおむね維持し、被害を抑制しました。':score>=50?'復旧の基盤は確保しましたが、改善の余地があります。':'連鎖被害が都市機能に大きく影響しました。')+'</p><ul class="report-list"><li><span>住民安全</span><b>'+Math.round(S.safe)+'%</b></li><li><span>インフラ</span><b>'+infra+'%</b></li><li><span>市民信頼</span><b>'+Math.round(S.trust)+'%</b></li><li><span>残予算</span><b>'+Math.round(C.budget-S.spent)+'</b></li></ul>';Q('#report-dialog').showModal();render()};window.onresize=resize;reset();resize();setInterval(step,500)})();